name: Build Android
on:
  workflow_dispatch:

jobs:
  build-aar:
    name: Build AAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Free up space by removing unnecessary folders
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Setup Node.js 16.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Build AAR
        run: docker run --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android /bin/sh -c "./gradlew --debug --stacktrace installArchives"
